import { RankTagStyle } from "@/lib/rank-tag-config";

// This config uses local file paths for server-side rendering.
// Make sure your image files are located in the 'public/rank-tag-tiles/' directory.

/** Server-side (filesystem-relative, no leading slash) mirror of `ICON_BACKGROUNDS` in rank-tag-config.ts. */
export const ICON_BACKGROUNDS_SERVER: Record<string, string> = {
  rounded: "rank-tag-tiles/round_icon.png",
  squared: "rank-tag-tiles/squire_icon.png",
  "extra-rounded": "rank-tag-tiles/extra_round_icon.png",
  medieval: "rank-tag-tiles/medieval_icon.png",
  cartoon: "rank-tag-tiles/cartoon_icon.png",
  classic: "rank-tag-tiles/classic_icon.png",
  hourglass: "rank-tag-tiles/hourglass_icon.png",
  legacy: "rank-tag-tiles/legacy_icon.png",
  modern: "rank-tag-tiles/modern_icon.png",
  tapered: "rank-tag-tiles/tapered_icon.png",
};

export function getIconBackgroundUrlServer(styleId: string): string {
  return ICON_BACKGROUNDS_SERVER[styleId] ?? ICON_BACKGROUNDS_SERVER.rounded;
}

export const RANK_TAG_STYLES_SERVER: RankTagStyle[] = [
      {
        id: "rounded",
        name: "Rounded Corners",
        description: "",
        leftUrl: "rank-tag-tiles/lavy_bg.png",
        middleUrl: "rank-tag-tiles/stred_bg.png",
        rightUrl: "rank-tag-tiles/pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      },
      {
        id: "squared",
        name: "Squared",
        description: "",
        leftUrl: "rank-tag-tiles/sq_lavy_bg.png",
        middleUrl: "rank-tag-tiles/sq_stred_bg.png",
        rightUrl: "rank-tag-tiles/sq_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      },
      {
        id: "extra-rounded",
        name: "Extra Rounded",
        description: "",
        leftUrl: "rank-tag-tiles/rd_lavy_bg.png",
        middleUrl: "rank-tag-tiles/rd_stred_bg.png",
        rightUrl: "rank-tag-tiles/rd_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      },
      {
        id: "medieval",
        name: "Medieval",
        description: "",
        leftUrl: "rank-tag-tiles/sg_lavy_bg.png",
        middleUrl: "rank-tag-tiles/sg_stred_bg.png",
        rightUrl: "rank-tag-tiles/sg_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 8,
        middleWidth: 6,
        rightWidth: 9,
      },
      {
        id: "cartoon",
        name: "Cartoon",
        description: "",
        leftUrl: "rank-tag-tiles/cartoon_lavy_bg.png",
        middleUrl: "rank-tag-tiles/cartoon_stred_bg.png",
        rightUrl: "rank-tag-tiles/cartoon_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      },
      {
        id: "classic",
        name: "Classic",
        description: "",
        leftUrl: "rank-tag-tiles/classic_lavy_bg.png",
        middleUrl: "rank-tag-tiles/classic_stred_bg.png",
        rightUrl: "rank-tag-tiles/classic_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      },
      {
        id: "hourglass",
        name: "Hourglass",
        description: "",
        leftUrl: "rank-tag-tiles/hourglass_lavy_bg.png",
        middleUrl: "rank-tag-tiles/hourglass_stred_bg.png",
        rightUrl: "rank-tag-tiles/hourglass_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      },
      {
        id: "legacy",
        name: "Legacy",
        description: "",
        leftUrl: "rank-tag-tiles/legacy_lavy_bg.png",
        middleUrl: "rank-tag-tiles/legacy_stred_bg.png",
        rightUrl: "rank-tag-tiles/legacy_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      },
      {
        id: "modern",
        name: "Modern",
        description: "",
        leftUrl: "rank-tag-tiles/modern_lavy_bg.png",
        middleUrl: "rank-tag-tiles/modern_stred_bg.png",
        rightUrl: "rank-tag-tiles/modern_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      },
      {
        id: "tapered",
        name: "Tapered",
        description: "",
        leftUrl: "rank-tag-tiles/tapered_lavy_bg.png",
        middleUrl: "rank-tag-tiles/tapered_stred_bg.png",
        rightUrl: "rank-tag-tiles/tapered_pravy_bg.png",
        tileHeight: 12,
        leftWidth: 7,
        middleWidth: 6,
        rightWidth: 8,
      }
];
